In [1]:
import numpy as np

In [15]:
weird= np.array([3,4,5,6.0,"Bera"])

In [16]:
weird.dtype #object form

dtype('<U32')

In [23]:
weird= np.array([3,4,5,6.0,9])

In [24]:
weird.dtype
print (weird)

[3. 4. 5. 6. 9.]


In [25]:
weird=weird.astype("int64")

In [26]:
print(weird)

[3 4 5 6 9]


In [28]:
weird=np.array([3,4,5,6,7], dtype="int8") #its int64 as default
weird.dtype

dtype('int8')

In [31]:
date=np.array(["2025-05-18"])
date.dtype

dtype('<U10')

In [34]:
date=date.astype("datetime64")
date.dtype

dtype('<M8[D]')

In [36]:
date2=np.datetime64("2025-05-18", "D")
date2.dtype

dtype('<M8[D]')

In [41]:
matrix= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [42]:
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [44]:
matrix[3]

array([13, 14, 15, 16])

In [46]:
matrix[:,0]

array([ 1,  5,  9, 13])

In [49]:
matrix[1:3,2:]

array([[ 7,  8],
       [11, 12]])

In [52]:
np.random.randint(2,3,(4,4))

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [59]:
np.random.randint(0,8)

3

In [60]:
np.random.randint(0,8,(2,4))/10

array([[0.5, 0.7, 0.6, 0.3],
       [0.2, 0.5, 0.3, 0.4]])

In [61]:
million=np.arange(1_000_000)

In [62]:
million

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [64]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [68]:
np.linspace(10,20,12) #parts ints 10 to 20, 10 times, returns an array

array([10.        , 10.90909091, 11.81818182, 12.72727273, 13.63636364,
       14.54545455, 15.45454545, 16.36363636, 17.27272727, 18.18181818,
       19.09090909, 20.        ])

In [70]:
np.linspace(10,20,12).reshape(3,4) #turns it into a matrix

array([[10.        , 10.90909091, 11.81818182, 12.72727273],
       [13.63636364, 14.54545455, 15.45454545, 16.36363636],
       [17.27272727, 18.18181818, 19.09090909, 20.        ]])

In [72]:
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [73]:
matrix.reshape(2,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [74]:
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [76]:
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [77]:
matrix=matrix.reshape(2,8)

In [78]:
matrix

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [79]:
matrix=matrix.reshape(4,4)

In [80]:
m5=matrix.copy() #changes in m5 doesnt effect matrix

In [81]:
m6=matrix.view() # m6 is using matrix's address

In [83]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [84]:
np.ones(3)

array([1., 1., 1.])

In [85]:
np.full((3,3),12)

array([[12, 12, 12],
       [12, 12, 12],
       [12, 12, 12]])

In [86]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [87]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [88]:
np.eye(3,4,2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [89]:
np.diag([2,3,6,1])

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 1]])

In [92]:
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [91]:
np.diag(matrix)

array([ 1,  6, 11, 16])

In [93]:
np.diag(np.diag(matrix))

array([[ 1,  0,  0,  0],
       [ 0,  6,  0,  0],
       [ 0,  0, 11,  0],
       [ 0,  0,  0, 16]])

In [94]:
m2=np.full((5,5),19)
m3=np.full((5,6),2)
#m2+m3 i cant 

In [99]:
m3=m3.reshape(30)[:25].reshape(5,5)#take the first 25 index to shape 5x5 matrix

In [100]:
 m2+m3 #now i can sum

array([[21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21]])

In [106]:
m1=np.ones((5,5),"int16")

In [107]:
m1[0]=m1[0]*3

In [111]:
m5=np.arange(5).reshape(5,1)
m5

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [112]:
m6=m1*m5 #i can mult. mxn * n*p

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [113]:
m6*np.diag(m6)

array([[  1,  12,  33,  64],
       [  5,  36,  77, 128],
       [  9,  60, 121, 192],
       [ 13,  84, 165, 256]])

In [145]:
matrix9=np.random.randint(0,10,(5,5 ))
matrix9

array([[4, 3, 5, 4, 1],
       [3, 0, 4, 8, 2],
       [8, 2, 3, 6, 5],
       [9, 3, 6, 0, 5],
       [7, 4, 7, 2, 6]])

In [139]:
matrix9>5

array([[False,  True,  True, False,  True],
       [False,  True, False, False,  True],
       [False, False,  True,  True, False],
       [False, False,  True, False, False],
       [False,  True, False, False,  True]])

In [140]:
matrix9[matrix9>=5]

array([8, 9, 8, 9, 9, 8, 6, 6, 9, 8])

In [141]:
 matrix9[matrix9==2].size

6

In [142]:
matrix[(matrix!=0) & (matrix%2==0)] #even and not zero

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [143]:
 matrix[(matrix%2==0) | (matrix==1)] #even or one

array([ 1,  2,  4,  6,  8, 10, 12, 14, 16])

Trial

In [2]:
import numpy as np

In [7]:
a = np.array([[1, 2], [3, 4]])

In [4]:
r = a.ravel()
r[0] = 99

In [5]:
r

array([99,  2,  3,  4])

In [6]:
a

array([[99,  2],
       [ 3,  4]])

In [8]:
f = a.flatten()
f[0] = 100

In [9]:
f

array([100,   2,   3,   4])

In [10]:
a

array([[1, 2],
       [3, 4]])

In [11]:
a = np.array([[1, 2], [3, 4]])

In [12]:
print(np.sum(a))  

10


In [13]:
print(np.sum(a, axis=0))

[4 6]


In [14]:
print(np.sum(a, axis=1))

[3 7]


In [15]:
a = np.array([10, 3, 7, 2])
print(np.argmin(a)) #index of min

3


In [16]:
a = np.array([50, 10, 30])
indices = np.argsort(a)
print("indexis for sorting", indices)  # [1 2 0]
print("sorted:", a[indices])      # [10 30 50]

indexis for sorting [1 2 0]
sorted: [10 30 50]


In [36]:
b = np.array([0, 0, 0])
np.any(b>2) 
np.any(b==False)
np.any(b=='a')
np.all(b==0) #for all values
np.all(b>5)

np.False_

In [37]:
k = np.array([1, 2, 3, 4, 5])
m = np.where(k % 2 == 0, "even", "odd") #creates a new array based on the cond.
m

array(['odd', 'even', 'odd', 'even', 'odd'], dtype='<U4')

In [38]:
A = np.array([[2, 1], [1, 3]])
b = np.array([8, 13])

np.linalg.solve(A, b)

array([2.2, 3.6])

In [47]:
np.random.seed(55)
print(np.random.rand(3))

[0.09310829 0.97165592 0.48385998]
